package com.shinu.todo_app.entity;

import java.time.LocalDateTime;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

// This class represents the database table "todos"
// Each object of this class will be stored as a row in DB

@Entity
@Table(name = "todos")
public class Todo {

    // primary key of the table
    // auto-generated by database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    // title of todo task
    private String title;

    // extra details about todo
    private String description;

    // status of todo (PENDING / COMPLETED)
    @Enumerated(EnumType.STRING)
    private TodoStatus status;

    // stores when todo was created
    private LocalDateTime createdAt;

    // getter for id
    public long getId() {
        return id;
    }

    // setter for id
    public void setId(long id) {
        this.id = id;
    }

    // getter for title
    public String getTitle() {
        return title;
    }

    // setter for title
    public void setTitle(String title) {
        this.title = title;
    }

    // getter for description
    public String getDescription() {
        return description;
    }

    // setter for description
    public void setDescription(String description) {
        this.description = description;
    }

    // getter for status
    public TodoStatus getStatus() {
        return status;
    }

    // setter for status
    public void setStatus(TodoStatus status) {
        this.status = status;
    }

    // getter for createdAt timestamp
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    // setter for createdAt timestamp
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}