"""
Application error code constants.
"""


class ErrorCode:
    # Generic / fallback
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
    INVALID_OPERATION = "INVALID_OPERATION"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    FORBIDDEN_ACCESS = "FORBIDDEN_ACCESS"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_PENDING_APPROVAL = "ACCOUNT_PENDING_APPROVAL"
    ACCOUNT_REJECTED = "ACCOUNT_REJECTED"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    INVALID_SETUP_TOKEN = "INVALID_SETUP_TOKEN"
    SETUP_TOKEN_EXPIRED = "SETUP_TOKEN_EXPIRED"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED"

    # Doctor
    DOCTOR_NOT_FOUND = "DOCTOR_NOT_FOUND"
    DOCTOR_PROFILE_SYNC_MISSING = "DOCTOR_PROFILE_SYNC_MISSING"
    DUPLICATE_LICENSE = "DUPLICATE_LICENSE"
    DOCTOR_APPLICATION_NOT_FOUND = "DOCTOR_APPLICATION_NOT_FOUND"
    APPLICATION_ALREADY_REVIEWED = "APPLICATION_ALREADY_REVIEWED"
    DOCTOR_NOT_APPROVED = "DOCTOR_NOT_APPROVED"

    # Slot / Appointment
    SLOT_NOT_FOUND = "SLOT_NOT_FOUND"
    SLOT_NOT_AVAILABLE = "SLOT_NOT_AVAILABLE"
    SLOT_NOT_EDITABLE = "SLOT_NOT_EDITABLE"
    SLOT_NOT_DELETABLE = "SLOT_NOT_DELETABLE"
    SLOT_IN_PAST = "SLOT_IN_PAST"
    DUPLICATE_SLOT = "DUPLICATE_SLOT"
    APPOINTMENT_ALREADY_BOOKED = "APPOINTMENT_ALREADY_BOOKED"
    APPOINTMENT_NOT_FOUND = "APPOINTMENT_NOT_FOUND"
